---
- name: Remove automatically installed PVE Enterprise repo configuration
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    filename: pve-enterprise
    state: absent
    update_cache: false
  with_items:
    - "deb https://enterprise.proxmox.com/debian {{ ansible_distribution_release }} pve-enterprise"
    - "deb https://enterprise.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-enterprise"
    - "deb https://enterprise.proxmox.com/debian/ceph-quincy {{ ansible_distribution_release }} enterprise"
  when: "ansible_distribution_major_version | int <= 12"

- name: Remove automatically installed PVE Enterprise repo configuration
  ansible.builtin.deb822_repository:
    name: "{{ item.name }}"
    state: absent
    types: deb
    uris: "{{ item.uris }}"
    suites: "{{ ansible_distribution_release }}"
    components: "{{ item.components }}"
  loop:
    - { name: 'pve-enterprise', uris: 'https://enterprise.proxmox.com/debian/pve', components: ['pve-enterprise'] }
    - { name: 'ceph', uris: 'https://enterprise.proxmox.com/debian/{{ pve_ceph_debian_component }}', components: ['enterprise'] }
  when: "ansible_distribution_major_version | int > 12"
