---

- name: Remove Existing Docker  Directory (if it exists)
  ansible.builtin.shell: sudo rm -rf /etc/apt/sources.list.d/docker.list

- name: Download Docker GPG key securely
  ansible.builtin.shell: curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc


- name: Add Docker Module Repository
  ansible.builtin.deb822_repository:
    name: docker
    types: [deb]
    uris: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
    signed_by: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    suites: ["{{ ansible_distribution_release | lower }}"]
    components: [stable]
    state: present
    enabled: yes

- name: "Update apt cache (Debian Family)"
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Install docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - containerd.io
    state: present
    update_cache: yes
