---

- name: Remove Existing Docker  Directory (if it exists)
  ansible.builtin.shell: sudo rm -rf /etc/apt/keyrings

- name: Remove Existing Docker  Directory (if it exists)
  ansible.builtin.shell: sudo rm -rf /etc/apt/sources.list.d/docker.list

- name: Download Docker GPG key securely
  ansible.builtin.shell: curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc

- name: Install docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - containerd.io
    state: present
    update_cache: yes
