- name: Copy mopidy template
  template:
    src: mopidy.j2
    dest: /etc/mopidy/mopidy.cfg
    owner: jasper 
    group: jasper
    mode: '0644'



    # Start and enable Snapserver
- name: Start and enable snapserver
  service:
    name: snapserver
    state: stopped
    enabled: true

- name: Copy snapserver template
  template:
    src: snapserver.j2
    dest: /etc/snapserver.conf
    owner: jasper 
    group: jasper
    mode: '0755'


    # Start and enable Snapserver
- name: Restart snapserver
  service:
    name: snapserver
    state: restarted
    enabled: true


