


- name: Install Python mopidy extentions
  ansible.builtin.pip:
    name:
      - mopidy-mpd
      - mopidy-muse
      - mopidy-mpris
      - mopidy-tunein
      - mopidy-iris
      - mopidy-musicbox-webclient
      - mopidy-jellyfin
      - mopidy-pibox
    state: present
    break_system_packages: true

- name: Install mopidy Spotify Build Deps
  ansible.builtin.pip:
    name:
      - pygobject
      - pycairo
    state: present
    break_system_packages: true
  
- name: Download uv to build mopidy spotify from source
  ansible.builtin.shell:
    cmd: "curl -LsSf https://astral.sh/uv/install.sh | sh"

- name: make a directory to build mopidy spotify into
  ansible.builtin.file:
    path: /tmp/mopidy-spotify
    owner: jasper
    group: jasper
    mode: '644'

- name: Clone a Git repository for mopidy-spotify
  ansible.builtin.git:
    repo: 'https://github.com/mopidy/mopidy-spotify'
    dest: /tmp/mopidy-spotify
    version: main

- name: build mopidy-spotif
  ansible.builtin.command:
    cmd: uv sync 
    chdir: /tmp/mopidy-spotify
  environment:
    UV_PROJECT_ENVIRONMENT: /tmp/mopidy-spotify/.venv


- name: Check if Mopidy-Spotify extension is installed
  ansible.builtin.shell: mopidyctl deps | grep -i spotify
  register: mopidy_spotify_check
  failed_when: false
  changed_when: false
  check_mode: false

- name: Install Spotify Gstreamer plugin 
  ansible.builtin.get_url:
    url: 'https://github.com/mopidy/gst-plugins-rs-build/releases/download/gst-plugin-spotify_{{spotify_version}}-alpha%2Bspotify-logging.b9abdbc/gst-plugin-spotify_{{spotify_version}}-alpha+spotify-logging.b9abdbc-0mopidy1_amd64.deb'
    dest: /tmp/gst-plugin-spotify_{{spotify_version}}-alpha+spotify-logging.b9abdbc-0mopidy1_amd64.deb
    mode: '0440'  
  when: mopidy_spotify_check.rc == 0

- name: Install Mopidy Spotify Gstreamer .deb package
  ansible.builtin.apt:
    deb: /tmp/gst-plugin-spotify_{{spotify_version}}-alpha+spotify-logging.b9abdbc-0mopidy1_amd64.deb
  when: mopidy_spotify_check.rc == 0
