- name: Install Mopidy Packages
  apt:
    name: 
     - mopidy
     - mopidy-alsamixer
    update_cache: yes

- name: Install Snapserver Packages
  apt:
    name: 
     - snapserver
    update_cache: yes


- name: Install MopidySpotify Build Deps
  apt:
    name: 
     - libcairo2-dev
     - cmake
     - git
     - python3-gi
     - libgirepository-2.0-dev
     - python3-gi-cairo
    update_cache: yes
