- name: Install Mopidy Packages
  apt:
    name: 
     - mopidy
     - mopidy-alsamixer
    update_cache: yes


- name: Install MopidySpotify Build Deps
  apt:
    name: 
     - libcairo2-dev
     - cmake
     - git
    update_cache: yes


