# Start and enable Mopidy
- name: Start and enable MooseFS mopidy
  service:
    name: mopidy
    state: started
    enabled: true

- name: Restart Mopidy
  ansible.builtin.systemd_service:
    name: mopidy
    state: restarted
  become: true 


# Start and enable Snapserver
- name: Start and enable snapserver
  service:
    name: snapserver
    state: started
    enabled: true

- name: Restart Snapserver
  ansible.builtin.systemd_service:
    name: snapserver
    state: restarted
  become: true 


