- name: Pull netiso docker image
  community.docker.docker_image:
    name: ghcr.io/tuxuser/netiso-srv-rs
    tag: latest
    source: pull

- name: Copy Docker Compose File for Netiso
  template:
    src: netiso.cfg.j2
    dest: /home/jasper/docker/docker-compose.yml
    owner: jasper
    group: jasper
    mode: '0644'

- name: Run `docker compose up` again
  community.docker.docker_compose_v2:
   project_src: /home/jasper/docker
  register: output
