---
- name: Install required system packages
  apt:
     name:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python3-pip
        - virtualenv
        - python3-setuptools
     state: latest
     update_cache: true

- name: Update apt and install docker-ce
  apt:
     name: docker-ce
     state: latest
     update_cache: true
