---
- name: Create VM from Proxmox Template
  hosts: jgpve6
  vars:
    vm_name: jg-chunkserver2
    proxmox_ip: 10.0.10.6
    hostname: jg-chunkserver2
    vmhostname: jgpve6.jaspergreenhill.com
    storage_zfs: zfs
    proxmox_pass: "" 
  tasks:
    - name: Install python3-pip
      ansible.builtin.apt:
        name: python3-pip
        state: present
      become: yes

    - name: Install setuptools module via pip
      ansible.builtin.pip:
        name: setuptools
        state: present
        break_system_packages: true
    - name: Install requests module via pip
      ansible.builtin.pip:
        name: requests
        state: present
        break_system_packages: true
    - name: Install proxmoxer module via pip
      ansible.builtin.pip:
        name: proxmoxer
        state: present
        break_system_packages: true 
    
    - name: Clone proxmox template
      community.proxmox.proxmox:
        node: jgpve6.jaspergreenhill.com
        api_user: "root@pam"
        api_password: "{{ proxmox_pass }}"
        api_host: "{{ proxmox_ip }}"
        api_port: 8006
        storage: "{{ storage_zfs }}"
        hostname: "{{vmhostname}}"
        clone: "127"
        hostname: "{{ vm_name }}"

    - name: wait 10 seconds
      ansible.builtin.pause:
        seconds: 10

    - name: Start VM
      community.proxmox.proxmox:
        node: proxmox
        api_user: "root@pam"
        api_password: "{{ proxmox_pass }}"
        api_host: "10.0.10.6"
        api_port: 8006
        name: "{{ vm_name }}"
        state: started

    - name: wait 20 seconds
      ansible.builtin.pause:
        seconds: 20

    - name: Update Hostname
      ansible.builtin.hostname:
        name: "{{ hostname }}.jaspergreenhill.com"

    - name: Reboot
      ansible.builtin.command: "init 6"
      ignore_errors: true

    - name: Pause for 30 seconds to wait for reboot
      ansible.builtin.pause:
        seconds: "10"
