---
- name: Configure Master Nodes
  hosts: k8smaster
  become: yes
  roles:
    - roles/jg_update_packages
    - roles/jg_k8s_packages
    - roles/jg_k8s_containerd
    - roles/jg_k8s_disableswap
    - roles/jg_k8s_kubecfg
    - roles/jg_k8s_modules
    - roles/jg_k8s_master
    - roles/jg_k8s_master_kubeadm
    - roles/jg_k8s_master_join

- name: Configure all Nodes
  hosts: k8s
  become: yes
  roles:
    - roles/jg_update_packages
    - roles/jg_k8s_packages
    - roles/jg_k8s_containerd
    - roles/jg_k8s_disableswap
    - roles/jg_k8s_kubecfg
    - roles/jg_k8s_modules
  vars:
    fqdn: jaspergreenhill.com
    user_jasper: jasper
    dnsserver: 10.0.40.3
    domainname: jg-dns.jaspergreenhill.com
  tasks:
  - name: System details
    ansible.builtin.debug: msg="{{ item }}"
    with_items:
    - "{{ ansible_hostname }}"
    - "{{ ansible_distribution_release }}"
