---
- hosts: pve
  become: yes
  roles:
    - roles/jg_pve_apt_repo
    - roles/jg_pve_network
    - roles/jg_pve_remove_nag
    - roles/jg_pve_pcipassthrough
  vars:
    pcie_passthrough:
      enable: true
      allow_unsafe_interrupts: false
      ids:
        - 10de:1c30
        - 10de:10f1
        - 10de:11bc
      blocklist:
        - nouveau
        - nvidafb
        - nvidia
        - radeon
        - amdgpu
        - i915
    pve_repository_line: "deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription"
    pve_repository:
      uris: http://download.proxmox.com/debian/pve
      suites: "{{ ansible_distribution_release }}"
      components: pve-no-subscription 
    search: ""
    dnsserver: 10.0.40.3
    domainname: jg-dns.jaspergreenhill.com
  tasks:
  - name: System details
    debug: msg="{{ item }}"
    with_items:
    - "{{ ansible_distribution }}"
    - "{{ ansible_distribution_version }}"
    - "{{ ansible_distribution_major_version }}"
    - "{{ ansible_distribution_release }}"
    - "{{ansible_processor}}"
    - "{{ ansible_default_ipv4.address }}"
  - name: Get PCIE devices list
    ansible.builtin.command: >-
      pvesh get /nodes/{{ ansible_facts.hostname }}/hardware/pci --output-format json
    changed_when: false
    register: pciedevices

  - name: Print available PCIE devices list
    ansible.builtin.debug:
      msg: "{{ available_pcie_devices }}"
    vars:
      search_query: "[?contains(vendor_name, '{{ search }}')]"
      available_pcie_devices: "{{ pciedevices.stdout | from_json | json_query(search_query) }}"
