---
- hosts: pve
  become: yes
  roles:
    - roles/jg_pve_apt_repo
    - roles/jg_pve_remove_nag
  vars:
    pve_repository_line: "deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription"
    pve_repository:
      uris: http://download.proxmox.com/debian/pve
      suites: "{{ ansible_distribution_release }}"
      components: pve-no-subscription 
  tasks:
  - name: System details
    debug: msg="{{ item }}"
    with_items:
    - "{{ ansible_distribution }}"
    - "{{ ansible_distribution_version }}"
    - "{{ ansible_distribution_major_version }}"
    - "{{ ansible_distribution_release }}"
