---
- hosts: pve
  become: yes
  roles:
   - roles/jg_pve_pcipassthrough
  vars:
    pcie_passthrough:
      enable: true
      allow_unsafe_interrupts: true
      ids:
        - 10de:11bc
      blocklist:
        - nvidia
        - radeon
        - amdgpu
        - i915
  tasks:
  - name: System details
    debug: msg="{{ item }}"
    with_items:
    - "{{ ansible_distribution }}"
    - "{{ ansible_distribution_version }}"
    - "{{ ansible_distribution_major_version }}"
    - "{{ ansible_distribution_release }}"
    - "{{ansible_processor}}"
    - "{{ ansible_default_ipv4.address }}"
