---
- hosts: servers
  become: yes
  roles:
    #- roles/jg_moosefs_repo 
    #- roles/jg_moosefs_client 
    - roles/jg_network
    - roles/jg_ntp
    #- roles/jg_update_packages
    - roles/jg_server_packages
    - roles/jg_users
    #- roles/jg_sshkey
    - roles/jg_apt_unattended_upgrades
    #- roles/jg_pki_cert
  vars:
   # ad_username:
   # ad_password:
    fqdn: jaspergreenhill.com
    user_jasper: jasper
    dnsserver: 10.0.40.3
    domainname: jg-dns.jaspergreenhill.com
    patch_update_scope: all
    patch_auto_reboot: true
    patch_schedule_oncalendar: "Thu *-*-* 03:30:00"
    patch_schedule_randomized_delay_sec: 600
    patch_auto_reboot_time: "04:30"
    patch_notify_email: jasper.greenhill@gmail.com
    patch_email_only_on_error: true
    patch_remove_unused_dependencies: true
  tasks:
  - name: System details
    ansible.builtin.debug: msg="{{ item }}"
    with_items:
    - "{{ ansible_hostname }}"
    - "{{ ansible_distribution_release }}"
