---

- name: Remove symbolic link to resolv.conf
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: absent
  become: true  

- name: Create resolv.conf
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: touch
    mode: '0644'

- name: Clear Lines in File domain name
  lineinfile: 
    dest: /etc/resolv.conf 
    state: absent 
    regexp: "search"

- name: Clear Lines in File nameserver
  lineinfile: 
    dest: /etc/resolv.conf 
    state: absent 
    regexp: "nameserver"

- name: Edit Resolv.conf
  ansible.builtin.blockinfile:
    path: /etc/resolv.conf
    block: |
      search {{domainname}}
      nameserver {{dnsserver}}
    marker: "# {mark} ANSIBLE MANAGED BLOCK nameserver"
