---
    - name: Remove hosts file
      ansible.builtin.file:
        path: /etc/resolv.conf
        state: absent
      become: true

    - name: Create hosts file
      ansible.builtin.file:
        path: /etc/resolv.conf
        state: touch 

    - name: Change the hostname to our standard
      hostname:
        name="{{ inventory_hostname }}"
      when:
        ansible_fqdn != ansible_ssh_host
     
    - name: Fix /etc/hosts removing the old hostname
      tags:
        - hosts
      lineinfile:
        state=present
        dest=/etc/hosts
        line="{{ inventory_hostname }} {{ ansible_hostname }}"
        regexp="^{{ ansible_default_ipv4.address }}"
      when:
        ansible_fqdn != inventory_hostname

    - name: Validate ansible_fqdn == inventory_hostname
      tags:
        - validate
      assert:
        that:
          ansible_fqdn == inventory_hostname
