---
- name: Configure hostname template 
  template:
    src: hostname.j2
    dest: /etc/hostname
    owner: root
    group: root
    mode: '0644'


- name: Ensure the hostname is applied to the current session
  ansible.builtin.hostname:
    name: "{{ ansible_hostname }}"
  changed_when: false

