---
- name: Create ArgoCD Namespace
  shell: kubectl create namespace argocd  
  ignore_errors: yes  

- name:  set Config Namespace to Argocd
  shell: kubectl config set-context --current --namespace=argocd
  ignore_errors: yes  

- name: Apply ArgoCD
  shell: kubectl apply -n argocd --server-side --force-conflicts -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  ignore_errors: yes  


