---

- name: Check if the 'argocd' namespace exists
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Namespace
    name: argocd
  register: argocd_ns


- name: Create ArgoCD Namespace
  shell: kubectl create namespace argocd  
  ignore_errors: yes  
  when: argocd_ns.rc != 0

- name:  set Config Namespace to Argocd
  shell: kubectl config set-context --current --namespace=argocd
  ignore_errors: yes  

- name: Apply ArgoCD
  shell: kubectl apply -n argocd --server-side --force-conflicts -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  ignore_errors: yes  


