
- name: Copy nginx checkrr config file 
  template:
    src: checkrr.conf
    dest: /home/mediauser/docker/nginx/config/nginx/site-confs/checkrr.conf 
    owner: mediauser
    group: mediauser
    mode: '0644'

- name: Copy nginx joplin config file 
  template:
    src: joplin.conf
    dest: /home/mediauser/docker/nginx/config/nginx/site-confs/joplin.conf 
    owner: mediauser
    group: mediauser
    mode: '0644'

- name: Copy nginx jdownloader config file 
  template:
    src: jdownloader.conf
    dest: /home/mediauser/docker/nginx/config/nginx/site-confs/jdownloader.conf 
    owner: mediauser
    group: mediauser
    mode: '0644'

- name: Copy nginx tvheadend config file 
  template:
    src: tvheadend.conf
    dest: /home/mediauser/docker/nginx/config/nginx/site-confs/tvheadend.conf 
    owner: mediauser
    group: mediauser
    mode: '0644'  

- name: Copy nginx dispatcharr-us config file 
  template:
    src: dispatcharr-us.conf
    dest: /home/mediauser/docker/nginx/config/nginx/site-confs/dispatcharr-us.conf 
    owner: mediauser
    group: mediauser
    mode: '0644'

- name: Copy nginx dispatcharr-uk config file 
  template:
    src: dispatcharr-uk.conf
    dest: /home/mediauser/docker/nginx/config/nginx/site-confs/dispatcharr-uk.conf 
    owner: mediauser
    group: mediauser
    mode: '0644'

- name: Copy nginx dispatcharr config file 
  template:
    src: dispatcharr.conf
    dest: /home/mediauser/docker/nginx/config/nginx/site-confs/dispatcharr.conf 
    owner: mediauser
    group: mediauser
    mode: '0644'

- name: Copy nginx seedsyncarr config file 
  template:
    src: seedsyncarr.conf
    dest: /home/mediauser/docker/nginx/config/nginx/site-confs/seedsyncarr.conf 
    owner: mediauser
    group: mediauser
    mode: '0644'

- name: Copy nginx keycloak config file 
  template:
    src: keycloak.conf
    dest: /home/mediauser/docker/nginx/config/nginx/site-confs/keycloak.conf 
    owner: mediauser
    group: mediauser
    mode: '0644'

- name: Copy nginx technitium config file 
  template:
    src: dns.conf
    dest: /home/mediauser/docker/nginx/config/nginx/site-confs/dns.conf 
    owner: mediauser
    group: mediauser
    mode: '0644'
