---
- name: Install Packages 
  apt:
    pkg:
      - stress
      - linux-firmware
      - neovim
      - fastfetch
- name: Install file archive and compression tools
  apt:
    pkg:
      - unzip
      - zip
      - xz-utils
      - tar
      - pristine-tar
      - gzip
      - bzip2
      - p7zip-full
      - p7zip
      - lzop
      - cpio
      - cvs
      - rcs
      - unrar

- name: Install file transfer tools
  apt:
    pkg:
      - rsync
      - curl
      - lrzsz
      - wget

- name: Install network tools
  apt:
    pkg:
      - traceroute
      - mosh
      - telnet
      - finger
      - dnsutils
      - tshark
      - tcpdump
      - whois
      - ethtool
      - mtr
      - iputils-tracepath
      - iperf
      - host
      - ladvd

- name: "Gathering facts"
  ansible.builtin.setup:
  when: ansible_facts|default({}) == {}

- name: "Update apt cache (Debian Family)"
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: "Ensure qemu_guest_agent is installed"
  become: true
  ansible.builtin.package:
    name: qemu-guest-agent
    state: present
  when: ansible_system_vendor == 'QEMU'
