- name: Clone a Git repository for tdarr-inform 
  ansible.builtin.git:
    repo: 'https://github.com/deathbybandaid/tdarr_inform.git'
    dest: ~/docker/tdarr_inform


- name: Install Python Dependencies requirements.txt tdarr-inform
   ansible.builtin.pip:
     requirements: ~/docker/tdarr_inform/requirements.txt
   break_system_packages: true

- name: Install Python Dependencies web-requirements.txt tdarr-inform
   ansible.builtin.pip:
     requirements: ~/docker/tdarr_inform/web-requirements.txt
   break_system_packages: true

