---
- name: Install systemd-timesyncd
  apt:
    name: systemd-timesyncd
    update_cache: yes


- name: Enable systemd-timesyncd
  ansible.builtin.systemd_service:
    name: systemd-timesyncd
    state: started
    enabled: true
