---
- name: Update GRUB
  ansible.builtin.command: update-grub
  changed_when: true
  notify: Reboot

- name: Update initramfs
  ansible.builtin.command: update-initramfs -u
  changed_when: true
  notify: Reboot

- name: Reboot
  ansible.builtin.reboot:

- name: Restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
