---

- name: "Update apt cache (Debian Family)"
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"


- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Remove dependencies that are no longer required 
  ansible.builtin.apt:
    autoremove: yes
