---
- name: Check if node is already joined
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubeconfig_file

- name: Join Master Nodes
  ansible.builtin.shell: "{{ join_command }} --control-plane --certificate-key {{ certificate_key }}"
  when: not kubeconfig_file.stat.exists
  become: true
