---
- name: Copy join-command file to master nodes
  copy:
    src: /tmp/master-join-command
    dest: /tmp/master-join-command
    mode: 0755

- name: Check if node is already joined
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubeconfig_file

- name: Join Master Nodes
  ansible.builtin.shell: sh /tmp/master-join-command
  become: yes
  when: not kubeconfig_file.stat.exists
