---
- name: Check if node is already joined
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubeconfig_file

- name: Join Worker Nodes
  ansible.builtin.shell: "{{ join_command }}" 
  become: yes
  when: not kubeconfig_file.stat.exists
