---
# tasks file for ansible-role-moosefs
# Configure your MooseFS cluster.

- name: Configure the main metalogger configuration
  template:
    src: mfsmetalogger.cfg.j2
    dest: /etc/mfs/mfsmetalogger.cfg
    owner: mfs
    group: mfs
    mode: '0644'
  when: "'chunkservers' in group_names"

- name: Configure the main chunkserver configuration
  template:
    src: mfschunkserver.cfg.j2
    dest: /etc/mfs/mfschunkserver.cfg
    owner: mfs
    group: mfs
    mode: '0644'
  when: "'chunkservers' in group_names"


- name: Get list of active mount points
  ansible.builtin.setup:
   filter: "ansible_mounts"

- name: Create a list of mount point paths
  ansible.builtin.set_fact:
    mount_points: "{{ ansible_facts.ansible_mounts | map(attribute='mount') | list }}"

- name: Find all empty directories
  ansible.builtin.find:
    paths: "{{ target_directory }}"
    file_type: directory
    hidden: true
    recurse: true
  register: found_dirs

- name: Filter out non-empty directories and mount points
  ansible.builtin.set_fact:
    empty_unmounted_dirs: >-
        {{
            found_dirs.files
            | selectattr('size', 'equalto', 0)
            | map(attribute='path')
            | difference(mount_points)
          }}

- name: Remove empty and non-mounted directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: "{{ empty_unmounted_dirs | sort(reverse=True) }}"  

- name: Build a list of bricks
  find:
    paths: /mnt/
    patterns: "mfsbrick.*,mfsbrickpro.*"
    file_type: directory
  register: brick_list

- name: Configure the chunkserver brick list
  template:
    src: mfshdd.cfg.j2
    dest: /etc/mfs/mfshdd.cfg
    owner: mfs
    group: mfs
    mode: '0644'
  when: "'chunkservers' in group_names"

- name: Mark MooseFS as configured
  set_fact:
    moosefs_configured: true

