- name: Check if iptables is installed
  ansible.builtin.package:
    name: iptables
    state: present
  check_mode: yes
  register: package_check

- name: Install IPtables Packages
  apt:
    name: 
     - iptables
  update_cache: yes
  when: not package_check.stat.exists

- name: Allow outgoing TCP traffic to mfsmaster for chunkservers
  ansible.builtin.iptables:
    chain: OUTPUT
    protocol: tcp
    destination: "{{ moosefs_master_host }}"
    destination_port: "9420"
    jump: ACCEPT
    action: append
    comment: Allow outbound connection to MooseFS Master

- name: Allow outgoing TCP traffic to mfsmaster for metalogger
  ansible.builtin.iptables:
    chain: OUTPUT
    protocol: tcp
    destination: "{{ moosefs_master_host }}"
    destination_port: "9419"
    jump: ACCEPT
    action: append
    comment: Allow outbound connection to MooseFS Master
