---


- name: Copy Moosefs Chunkserver service template
  template:
    src: moosefs-chunkserver.service.j2
    dest: /usr/lib/systemd/system/moosefs-chunkserver.service
    owner: root
    group: root
    mode: '0644'
  when: "'chunkservers' in group_names"


- name: Copy Moosefs Metalogger service template
  template:
    src: moosefs-metalogger.service.j2
    dest: /usr/lib/systemd/system/moosefs-metalogger.service
    owner: root
    group: root
    mode: '0644'
  when: "'chunkservers' in group_names"

# Start and enable MooseFS chunkserver
- name: Start and enable MooseFS chunkserver
  service:
    name: moosefs-chunkserver
    state: started
    enabled: true
  when: "'chunkservers' in group_names"

# Start and enable MooseFS metalogger
- name: Start and enable MooseFS metalogger
  service:
    name: moosefs-metalogger
    state: started
    enabled: true
  when: "'chunkservers' in group_names"

- name: Reload Moosefs Chunkserver
  ansible.builtin.systemd:
    name: moosefs-chunkserver
    state: restarted
    daemon_reload: yes
