# tasks file for ansible-role-moosefs
# Make sure the brick directory is healthy and correctly configured
---
- name: Build a list of bricks
  find:
    paths: /mnt/
    patterns: "mfsbrick.*,mfsbrickpro.*"
    file_type: directory
  register: brick_list

- name: Ensure each brick folder exists and is owned correctly
  file:
    name: "{{ item.path }}/brick"
    state: directory
    owner: mfs
    group: mfs
    mode: '0750'
    recurse: yes
  when: "'moosefs_chunkserver' in group_names"
  loop: "{{ brick_list.files }}"
  no_log: true

- name: Remove .chunkdb to force a rescan 
  ansible.builtin.file:
    path: /mnt/mfsbrick.*/.chunkdb
    state: absent

- name: Find brick directories
  ansible.builtin.find:
    paths: /mnt
    patterns: 'mfsbrick.*'
    file_type: directory
  register: brick_dirs

- name: Find items inside the bricks not owned by mfs:mfs
  ansible.builtin.command:
    argv: >-
      {{
        ['find'] + (brick_dirs.files | map(attribute='path') | list) +
        ['-xdev', '(', '!', '-user', 'mfs', '-o', '!', '-group', 'mfs', ')']
       }}
  register: non_mfs_items
  changed_when: false
  check_mode: false
  no_log: true

- name: Set ownership to mfs:mfs on non-mfs items
  ansible.builtin.command:
    cmd: chown -R mfs:mfs "{{ item }}"
  loop: "{{ non_mfs_items.stdout_lines }}"
  no_log: false
  changed_when: true
