---


- name: Create Join Command and Token to Join Nodes
  ansible.builtin.command:
    cmd: kubeadm token create --print-join-command 
    creates: /tmp/kubeadm_output_join
  register: kubeadm_token_output
  become: true
  changed_when: false


- name: Generate the Join Command for Worker Nodes
  ansible.builtin.shell: cat /tmp/kubeadm_output_join  > /tmp/worker-join-command
  delegate_to: localhost

- name: Set permissions for the Join Executable
  file:
    path: /tmp/worker-join-command
    state: file
    mode: '0755'
  delegate_to: localhost


- name: Generate the Join Command for Master Nodes
  ansible.builtin.shell: cat /tmp/kubeadm_output_join | sed ':a;N;$!ba;s/\\\n\s*/ /g' | grep "kubeadm join" | sed -n '/kubeadm join.*--control-plane/p' > /tmp/master-join-command
  delegate_to: localhost

- name: Set permissions for the Join Executable
  file:
    path: /tmp/master-join-command
    state: file
    mode: '0755'
  delegate_to: localhost
