cilium_version: "1.19.12"
cilium_service_host: "jg-k8smaster1.jaspergreenhill.com"
cilium_service_port: 6443
cilium_namespace: "cilium"

cilium_bgp_peer_address: "172.16.10.1"
cilium_bgp_peer_as: 64512
cilium_bgp_local_as: 64512
cilium_bgp_name: "k8s-cluster"
cilium_bgp_peer_config_name: "router"

cilium_bgp_advertise_pool: "10.200.200.0/24"
