---
- name: Update Kubeadm Environment Variable
  ansible.builtin.command:
    cmd: sudo sed -i -e '/^\[Service\]/a Environment="KUBELET_EXTRA_ARGS=--fail-swap-on=false"' /usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf

- name: Pull kubeadm container images
  ansible.builtin.command:
    cmd: sudo kubeadm config images pull

- name: Check if control plane is initialized
  stat:
    path: /etc/kubernetes/manifests/kube-apiserver.yaml
  register: control_plane_manifest

- name: Initialize Kubernetes control plane
  ansible.builtin.command:
    cmd: kubeadm init --control-plane-endpoint=10.0.40.21 --node-name jg-k8smaster1 --pod-network-cidr={{ cni_network }} --upload-certs
    creates: /tmp/kubeadm_output
  register: kubeadm_init_output
  become: true
  changed_when: false
  when: not control_plane_manifest.stat.exists

- name: Set permissions for Kubernetes Admin
  file:
    path: /etc/kubernetes/admin.conf
    state: file
    mode: '0755'

- name: Check if kube config file exists
  stat:
    path: /etc/kubernetes/manifests/kube-apiserver.yaml
  register: kube_config_manifest

- name: create .kube directoryi and copy kube config file
  shell: "{{ item }}"
  when: not kube_config_manifest.stat.exists
  loop:
    - mkdir -p $HOME/.kube
    - cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    - chown $(id -u):$(id -g) $HOME/.kube/config

- name: Store Kubernetes initialization output to file
  copy:
    content: "{{ kubeadm_init_output.stdout }}"
    dest: /tmp/kubeadm_output
  become: true
  when: not control_plane_manifest.stat.exists
  delegate_to: localhost
