---

- name: "Install curl & gpg"
  package:
    name:
      - curl
      - gpg
    state: present

#- name: Check if Moosefs Key Already Exists
#  stat:
#   path: /etc/apt/keyrings/moosefs.gpg

#- name: "Get public key for MooseFS repository"
#  shell: "curl https://repository.moosefs.com/moosefs.key | gpg -o /etc/apt/keyrings/moosefs.gpg --dearmor" 

- name: Add MooseFS repo to sources list
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/moosefs.gpg] http://repository.moosefs.com/moosefs-4/apt/debian/{{ansible_distribution_release}}  {{ansible_distribution_release}} main" 
    state: present
    filename: "/etc/apt/sources.list.d/moosefs"

- name: Update apt cache
  apt:
    update_cache: yes
