- name: Remove moosefs at sources.list
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/moosefs.*
    state: absent



- name: Install Moosefs Chunkserver Packages
  apt:
    name: 
     - gpg
    update_cache: yes
