---


- name: "Add MooseFS 4 Community Repository"
  ansible.builtin.deb822_repository:
    name: moosefs
    types: [deb]
    uris: "https://repository.moosefs.com/moosefs-4/apt/{{ ansible_distribution}}/{{ansible_distribution_release}}"
    signed_by: "https://repository.moosefs.com/moosefs.key"
    suites: ["{{ ansible_distribution_release}}"]
    components: [main]
    state: present
    enabled: yes

- name: Update apt cache
  apt:
    update_cache: yes
