- name: Remove moosefs at sources.list
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/moosefs.list
    state: absent

- name: Remove moosefs at sources.sources
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/moosefs.sources
    state: absent

- name: Install gpg package
  apt:
    name: 
     - gpg
    update_cache: yes
